name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag sonils/planils-dashboard:$GITHUB_RUN_NUMBER  --tag sonils/planils-dashboard:latest
    -
      name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to DockerHub Versioned Tag
      run: docker push sonils/planils-dashboard:$GITHUB_RUN_NUMBER
    - name: Push to DockerHub Latest Tag
      run: docker push sonils/planils-dashboard:latest
