name: Deploy Images to GHCR

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REPO_ACCESS_TOKEN}}

      - name: 'Build & Deploy To Inventory'
        run: |
          docker build . --tag ghcr.io/sonils/planils-dashboard:latest --tag ghcr.io/sonils/planils-dashboard:${{ github.run_number }}
          docker push ghcr.io/sonils/planils-dashboard:${{ github.run_number }}
          docker push ghcr.io/sonils/planils-dashboard:latest
